// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnTy4uPnQTG-bnFBIHwSnyAFJW8NwvmlI',
    appId: '1:33274093810:web:09332deb608de9b3b1706b',
    messagingSenderId: '33274093810',
    projectId: 'goodwill-bb34b',
    authDomain: 'goodwill-bb34b.firebaseapp.com',
    storageBucket: 'goodwill-bb34b.firebasestorage.app',
    measurementId: 'G-20EXBCZTJ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7qGjRLDodpCvDro3cnyCMHwtPq2y7k-E',
    appId: '1:33274093810:android:46bf74d78cff9727b1706b',
    messagingSenderId: '33274093810',
    projectId: 'goodwill-bb34b',
    storageBucket: 'goodwill-bb34b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx_1-LxTiqrcYzbXtkqK2nJ5V2cbITLQA',
    appId: '1:33274093810:ios:29ca10e4b5c11bfcb1706b',
    messagingSenderId: '33274093810',
    projectId: 'goodwill-bb34b',
    storageBucket: 'goodwill-bb34b.firebasestorage.app',
    iosClientId: '33274093810-a92q0st8t4knnpr42dkl1quin8c9nctc.apps.googleusercontent.com',
    iosBundleId: 'com.example.goodwill',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx_1-LxTiqrcYzbXtkqK2nJ5V2cbITLQA',
    appId: '1:33274093810:ios:29ca10e4b5c11bfcb1706b',
    messagingSenderId: '33274093810',
    projectId: 'goodwill-bb34b',
    storageBucket: 'goodwill-bb34b.firebasestorage.app',
    iosClientId: '33274093810-a92q0st8t4knnpr42dkl1quin8c9nctc.apps.googleusercontent.com',
    iosBundleId: 'com.example.goodwill',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnTy4uPnQTG-bnFBIHwSnyAFJW8NwvmlI',
    appId: '1:33274093810:web:3b297f12ceebd8a3b1706b',
    messagingSenderId: '33274093810',
    projectId: 'goodwill-bb34b',
    authDomain: 'goodwill-bb34b.firebaseapp.com',
    storageBucket: 'goodwill-bb34b.firebasestorage.app',
    measurementId: 'G-SV7YKHFR2M',
  );
}
